package com.example.vibemoney.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage {
    CHINESE, ENGLISH
}

data class AppStrings(
    val settings: String,
    val activeLedger: String,
    val name: String,
    val budget: String,
    val type: String,
    val llmConfig: String,
    val llmDesc: String,
    val apiUrl: String,
    val apiKey: String,
    val apiModel: String,
    val saveSettings: String,
    val persistNote: String,
    val welcome: String,
    val aiDriven: String,
    val createFirst: String,
    val newLedger: String,
    val setupBudget: String,
    val ledgerName: String,
    val ledgerType: String,
    val totalBudget: String,
    val fixedExpenses: String,
    val createLedger: String,
    val cancel: String,
    val remaining: String,
    val dailyLimit: String,
    val spent: String,
    val netSpent: String,
    val recentTransactions: String,
    val aiSummary: String,
    val aiAssistant: String,
    val chooseAnalysis: String,
    val apiAnalysis: String,
    val copyPrompt: String,
    val apiNotConfigured: String,
    val thinking: String,
    val close: String,
    val back: String,
    val addTransaction: String,
    val note: String,
    val amount: String,
    val category: String,
    val expense: String,
    val income: String,
    val save: String,
    val daily: String,
    val temporary: String,
    val special: String,
    val language: String,
    val selectLanguage: String,
    val week: String,
    val month: String,
    val quarter: String,
    val year: String,
    val promptCopied: String,
    val finished: String,
    val ledgerExpired: String,
    val about: String,
    val version: String,
    val aiPowered: String,
    val balance: String,
    val noSuggestion: String,
    val catFood: String,
    val catTransport: String,
    val catShopping: String,
    val catBills: String,
    val catGeneral: String
)

val zhStrings = AppStrings(
    settings = "设置",
    activeLedger = "当前账本",
    name = "名称",
    budget = "预算",
    type = "类型",
    llmConfig = "大模型 API 配置",
    llmDesc = "配置自定义 LLM API 用于消费分析",
    apiUrl = "API 地址",
    apiKey = "API 密钥",
    apiModel = "API 模型",
    saveSettings = "保存设置",
    persistNote = "注：设置已本地持久化，下次分析时生效。",
    welcome = "VibeMoney",
    aiDriven = "AI 驱动的多账本理财",
    createFirst = "创建首个账本",
    newLedger = "新建账本",
    setupBudget = "设置您的预算",
    ledgerName = "账本名称",
    ledgerType = "账本类型",
    totalBudget = "总预算",
    fixedExpenses = "固定开支",
    createLedger = "创建账本",
    cancel = "取消",
    remaining = "剩余预算",
    dailyLimit = "建议每日支出",
    spent = "累计支出",
    netSpent = "本期净支出",
    recentTransactions = "最近流水",
    aiSummary = "AI 总结",
    aiAssistant = "AI 财务助手",
    chooseAnalysis = "请选择分析方式：",
    apiAnalysis = "API 自动分析",
    copyPrompt = "复制分析提示词",
    apiNotConfigured = "未在设置中配置 API Key",
    thinking = "深度分析账单中...",
    close = "关闭",
    back = "返回选项",
    addTransaction = "添加流水",
    note = "备注",
    amount = "金额",
    category = "分类",
    expense = "支出",
    income = "收入",
    save = "保存",
    daily = "日常",
    temporary = "临时",
    special = "专项",
    language = "语言",
    selectLanguage = "选择语言",
    week = "周",
    month = "月",
    quarter = "季",
    year = "年",
    promptCopied = "提示词已复制",
    finished = "已结束",
    ledgerExpired = "此账本已结束",
    about = "关于 VibeMoney",
    version = "版本 1.0.0",
    aiPowered = "Powered by Gemini AI",
    balance = "当前余额",
    noSuggestion = "预算已用尽",
    catFood = "餐饮",
    catTransport = "交通",
    catShopping = "购物",
    catBills = "账单",
    catGeneral = "其他"
)

val enStrings = AppStrings(
    settings = "Settings",
    activeLedger = "Active Ledger",
    name = "Name",
    budget = "Budget",
    type = "Type",
    llmConfig = "LLM API Configuration",
    llmDesc = "Configure your custom LLM API for spending analysis.",
    apiUrl = "API URL",
    apiKey = "API Key",
    apiModel = "API Model",
    saveSettings = "Save API Settings",
    persistNote = "Note: Settings are persisted locally. Changes take effect on next AI analysis.",
    welcome = "VibeMoney",
    aiDriven = "AI Driven Multi-Ledger Finance",
    createFirst = "Create Your First Ledger",
    newLedger = "New Ledger",
    setupBudget = "Setup your budget",
    ledgerName = "Ledger Name",
    ledgerType = "Ledger Type",
    totalBudget = "Total Budget",
    fixedExpenses = "Fixed Expenses",
    createLedger = "Create Ledger",
    cancel = "Cancel",
    remaining = "Remaining",
    dailyLimit = "Daily Limit",
    spent = "Spent",
    netSpent = "Net Spent",
    recentTransactions = "Recent Transactions",
    aiSummary = "AI Summary",
    aiAssistant = "AI Assistant",
    chooseAnalysis = "Choose analysis method:",
    apiAnalysis = "API Analysis",
    copyPrompt = "Copy Prompt",
    apiNotConfigured = "API Key not configured",
    thinking = "Analyzing...",
    close = "Close",
    back = "Back",
    addTransaction = "Add Transaction",
    note = "Note",
    amount = "Amount",
    category = "Category",
    expense = "Expense",
    income = "Income",
    save = "Save",
    daily = "Daily",
    temporary = "Temporary",
    special = "Special",
    language = "Language",
    selectLanguage = "Select Language",
    week = "Week",
    month = "Month",
    quarter = "Quarter",
    year = "Year",
    promptCopied = "Prompt Copied",
    finished = "Finished",
    ledgerExpired = "Ledger Expired",
    about = "About VibeMoney",
    version = "Version 1.0.0",
    aiPowered = "Powered by Gemini AI",
    balance = "Balance",
    noSuggestion = "Budget Exhausted",
    catFood = "Food",
    catTransport = "Transport",
    catShopping = "Shopping",
    catBills = "Bills",
    catGeneral = "General"
)

val LocalAppStrings = staticCompositionLocalOf { zhStrings }

@Composable
@ReadOnlyComposable
fun getString(): AppStrings = LocalAppStrings.current
